# Stage 1: Use Maven for building
FROM maven:3-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Satge 2: Use OpenJDK for running
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/yipi-0.0.1-SNAPSHOT.jar yipi.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","yipi.war"]